package com.jiramanager.web;

import com.jiramanager.model.FeatureDesignDoc;
import com.jiramanager.repository.FeatureDesignDocRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Serves each Feature's uploaded HTML design doc ({@link FeatureDesignDoc}) for in-browser
 * viewing. Reachable only by an authenticated session — this endpoint isn't a Vaadin
 * {@code @Route}, so it relies on {@code SecurityConfig}'s {@code VaadinWebSecurity} base
 * behavior, which requires authentication for any request not explicitly permitted.
 *
 * <p><b>Deliberately unsandboxed (revisit before any public/shared deployment):</b> this app
 * currently runs local-only, for one small trusted team, and the uploaded file is generated by
 * the team's own external tooling from their own Jira/Confluence data — not an arbitrary
 * public upload. Per explicit product decision, the doc is served plain (full script execution,
 * same origin) so it renders/behaves exactly as authored, with no `Content-Security-Policy`
 * restriction. If this app is ever exposed beyond that (published, opened to untrusted uploaders,
 * multi-tenant, etc.), reintroduce a `Content-Security-Policy: sandbox` header here first — it
 * blocks script execution and cookie/session access for served content while still rendering
 * headings/tables/inline CSS normally (same effect as loading the doc in a fully sandboxed
 * iframe), which is the standard mitigation for rendering untrusted uploaded HTML safely.
 */
@RestController
@RequestMapping("/design-docs")
@RequiredArgsConstructor
public class DesignDocController {

    private final FeatureDesignDocRepository designDocRepo;

    /** Latest uploaded version for the Feature. */
    @GetMapping("/{featureId}")
    public ResponseEntity<Resource> viewLatest(@PathVariable Long featureId) {
        return serve(designDocRepo.findTopByFeature_IdOrderByVersionDesc(featureId).orElse(null));
    }

    /** One specific past version — for tracing/comparing against the current doc. */
    @GetMapping("/{featureId}/{version}")
    public ResponseEntity<Resource> viewVersion(@PathVariable Long featureId, @PathVariable int version) {
        return serve(designDocRepo.findByFeature_IdAndVersion(featureId, version).orElse(null));
    }

    private ResponseEntity<Resource> serve(FeatureDesignDoc doc) {
        if (doc == null || doc.getFilePath() == null) {
            return ResponseEntity.notFound().build();
        }

        Path path = Path.of(doc.getFilePath());
        if (!Files.exists(path)) {
            return ResponseEntity.notFound().build();
        }

        String fileName = doc.getFileName() != null ? doc.getFileName() : "design.html";
        return ResponseEntity.ok()
                .contentType(MediaType.parseMediaType("text/html;charset=UTF-8"))
                .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"" + fileName + "\"")
                .body(new FileSystemResource(path));
    }
}
